### ISSUE TITLE
Milestone 2 Features

### ISSUE THREAD

**Issue by jonthemango** [jonthemango/uber_sante#20]
- [x] The system must provide an integrated interface with more than one medical clinic.
- [x]  New patients can be easily added into the system health care database.
- [x] Doctors and nurses can be assigned to specific clinic.
- [x] Different clinics with internal representation of schedule, number of personal (doctors, nurses) and
rooms.
